POST http://localhost:3333/events
content-type: application/json

{
    "title": "Role dos amigos",
    "details": "Vamos jogar um futebolzinho",
    "maximumAttendees": 100
}

###
GET http://localhost:3333/events

###
GET http://localhost:3333/events/01b8f4e1-6c75-4977-ad63-a4d238c72de0

###
POST http://localhost:3333/events/01b8f4e1-6c75-4977-ad63-a4d238c72de0/attendees
content-type: application/json

{
    "name": "Fernanda",
    "email": "Fern@gmail.com"
}

###
GET http://localhost:3333/attendees/6/badge

###
POST http://localhost:3333/attendees/6/checkin
Content-Type: application/json

{
    
}

###
GET http://localhost:3333/events/01b8f4e1-6c75-4977-ad63-a4d238c72de0/attendees